### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by yawn** [yawn/ykoath#17]
As it says above. I tried a few times to push PRs forward but I simply have zero time to handle OSS projects. LMK if there is some via email.

**Comment by yawn** [comment]
@akerl came forward and proposed to take up maintenance. Thanks a ton for doing this @akerl and feel free to close this ticket unless you want to discuss specifics!

**Comment by akerl** [comment]
👍 

Thanks @yawn!

I'll carve out some time this weekend to poke at the existing open items. For what it's worth, part of that will be cleaning up my branch in https://github.com/yawn/ykoath/pull/16 and merging it.

Once that's in, will probably tag a new version, partly so I can use it but also to confirm that the Github actions flow is sorted out.
